### ISSUE TITLE
ApiProviders causes craft to crash

### ISSUE THREAD

**Issue by oseintow** [MasoniteFramework/craft#10]
Adding `ApiProvider,`  to providers causes craft to crash. 

Trying to add `entry` to craft. Below is the error.

```
WARNING: 'module' object is not callable

Traceback (most recent call last):
  File "/usr/local/bin/craft", line 7, in <module>
    from masonite_cli.application import application
  File "/usr/local/lib/python3.7/site-packages/masonite_cli/application.py", line 39, in <module>
    from wsgi import container
  File "/Users/oseintow/Sites/masonite/wsgi.py", line 41, in <module>
    located_provider = provider()
TypeError: 'module' object is not callable
```

**Comment by josephmancuso** [comment]
ah. You'll have to go one level deeper then for now till i come out with a fix. Something like `from entry.provider.ApiProvider import ApiProvider`

**Comment by oseintow** [comment]
The doc needs to be updated.

**Comment by josephmancuso** [comment]
fixed :)

**Comment by oseintow** [comment]
This is what i get now. I don't get the full list of the commands

```
➜  masonite craft

WARNING: No module named 'entry.provider'

Craft Version: 2.0.11

Usage:
  command [options] [arguments]

Options:
  -h, --help                      Display this help message
  -q, --quiet                     Do not output any message
  -V, --version                   Display this application version
      --ansi                      Force ANSI output
      --no-ansi                   Disable ANSI output
  -n, --no-interaction            Do not ask any interactive question
  -v|vv|vvv, --verbose[=VERBOSE]  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help     Displays help for a command
  install  Installs all of Masonite's dependencies
  list     Lists commands
  new      Creates a new Masonite project
  package  Creates a new package

```

**Comment by josephmancuso** [comment]
`from entry.providers.ApiProvider import ApiProvider`

it's `providers` not `provider`

**Comment by josephmancuso** [comment]
my mistake

**Comment by oseintow** [comment]
Thanks. works now.
